"""add user groups and targeting rules

Revision ID: 7e76c6e15e98
Revises: c22ac771625a
Create Date: 2026-07-14 16:45:54.992976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e76c6e15e98'
down_revision: Union[str, Sequence[str], None] = 'c22ac771625a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('targeting_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    op.drop_table('targeting_rules')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
